### ISSUE TITLE
Update PCA hover overlay with gene names

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium-ui#13]
This would make it more intuitive to look at for the biologist exploring their dataset.

**Comment by VCFG** [comment]
hi guys, I think I've worked out how to use this program! I see your dilemma, you need to define the way to ID something no matter what it is. so you could go with gene name_si (e.g RHOA_si), but then it is useful to use the entrez gene ID number. will you be able to click an extension to get that (I say this because some targets use a common alias and a formal name). otherwise, then you can have compound_X (say someone has done a dose curve and needs to know the concentration X), or else someone has done a multi-drug synthetic lethal screen, we'd need to know RHOA_si_DMSO (control) and RHOA_si_DOX or RHOA_si_EPI (2 drugs) (this scenario is a screen we have done). I would imagine we'd want all those clustered on the one view because you'd want to see what clusters in the drug treatments as same and different (to the drugs and of course to control). I have had a screener knockdown a gene, then do the genome screen over the top of that, so in that case we'd go with RHOA_si_RPS19 and RHOA_si_OTP (the control). I don't have an easy answer, there are many permutations. what if there was a dropdown box that let you select compound or RNAi, because after that you don't need to add the si extension, just the gene symbol. you will still need to know the control and drug if it was the dox and epi comparison above.  can a drop down box give you some flexibility. I'd definitely want to see it go out to further information about the target (but that's your plan).
