### ISSUE TITLE
Use Django for backend

### ISSUE THREAD

**Issue by starcalibre** [microscopium/microscopium-ui#66]
The more I think about, the more sense this makes to me. On top of the advantage of having access to the scipy stack in the backend, it'll be much easier for users to run the UI locally. All they'll need is Python, which should be installed on pretty much any bioinformaticians/biologists machine. You can't say the same for Node.js, which is still a JS hipster's thing (but an exciting one none the less IMO) :P

Coupled with an embedded database, everything would be able to run without any dependencies beyond Python! WHOAH! :D

Our backend isn't overly complicated, just a bunch of GET requests that query Mongo so it shouldn't be overly difficult. I'll just need to learn Django, which I'm happy to do because I'd like to add it to my skillset.

**Comment by jni** [comment]
I obviously love this idea, and am annoyed at myself that I didn't push more for it at the start. =) Plus, I can totally dictate style discussions now, rather than argue about the JS way of doing things and how much I dislike it. =P

This might seem like a slightly lower priority for the time being, though. What do you think? 

It also looks like the Bokeh guys have made a lot of progress since last year, and might have the right tools for us now.

**Comment by starcalibre** [comment]
Actioned in #73 except we chose Flask. Django was a little heavyweight for our requirements.
